server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # --- Gateway Logs ---
  - job_name: gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: envoy-gateway
          service: gateway-service
          __path__: /tmp/gateway.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            traceID: traceID
            time: start_time
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339
          action_on_failure: skip

  # --- Greeter Logs ---
  - job_name: greeter
    static_configs:
      - targets:
          - localhost
        labels:
          # Явно задаем service, чтобы он был в фильтрах Loki
          job: greeter-service
          service: greeter-service
          __path__: /tmp/greeter.log
    pipeline_stages:
      # Пытаемся распарсить как JSON, но не дропаем, если это текст
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            traceID: traceID
      - labels:
          level:
      # Если таймстемп не найден (текстовый лог), будет использовано время получения (skip)
      - timestamp:
          source: time
          format: RFC3339Nano
          action_on_failure: skip

  # --- Shell Logs ---
  - job_name: shell
    static_configs:
      - targets:
          - localhost
        labels:
          # Явно задаем service, чтобы он был в фильтрах Loki
          job: shell-service
          service: shell-service
          __path__: /tmp/shell.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            traceID: traceID
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339Nano
          action_on_failure: skip
