global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'envoy-gateway'
    static_configs:
      - targets: ['host.docker.internal:9901']

  - job_name: 'greeter-service'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'shell-service'
    static_configs:
      - targets: ['host.docker.internal:9002']
