server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Gateway логи
  - job_name: gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: gateway
          service: gateway-service
          __path__: /tmp/gateway.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            method: method
            path: path
            response_code: response_code
            duration: duration
            x_request_id: x_request_id
            x_b3_traceid: x_b3_traceid
            time: start_time
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339
          action_on_failure: skip

  # Greeter логи
  - job_name: greeter
    static_configs:
      - targets:
          - localhost
        labels:
          job: greeter
          service: greeter-service
          __path__: /tmp/greeter.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339Nano
          action_on_failure: skip

  # Shell логи
  - job_name: shell
    static_configs:
      - targets:
          - localhost
        labels:
          job: shell
          service: shell-service
          __path__: /tmp/shell.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339Nano
          action_on_failure: skip
