schema = 3

[mod]
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.3"
    hash = "sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.27.2"
    hash = "sha256-DVhStnXW+zJ2HUpdNUl2GU0Nkv6xN80gLiDXdxz5gwQ="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.66.1"
    hash = "sha256-bqHPaV9IV70itx63wqwgy2PtxMN0sn5ThVxDmiD7+Tk="
  [mod."github.com/prometheus/procfs"]
    version = "v0.16.1"
    hash = "sha256-OBCvKlLW2obct35p0L9Q+1ZrxZjpTmbgHMP2rng9hpo="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.63.0"
    hash = "sha256-kDRjKy2nJut38dHZbZy+haqSAh8qFgtTMqfe4y2WhCA="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.38.0"
    hash = "sha256-OU4EVEGwbopbYZLDBfAelR/4yjzfV+UVp4UFt3UvkOE="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.38.0"
    hash = "sha256-erOjiMK86nZaiKKo2DSpqEUBh8Y+PobuCxCTq7Bj2LM="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.38.0"
    hash = "sha256-uBogIdUQGMo4DLTs3CjYEVeYo+EhJu4wdSMhbX0jhfA="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.38.0"
    hash = "sha256-5W6Yd9nl/eyvL29e9hSfosISpxfSQcBAwkqI4htHWCg="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.38.0"
    hash = "sha256-Qxqf7LEbS8Znp8qeQPbgm0jeFVhZNwV2d5zuKysIKIQ="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.38.0"
    hash = "sha256-gNXUPmsPAw6JVH3YT/xwmRpn5QoDxyzc9kLe/5ldo0o="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.7.1"
    hash = "sha256-5VjS+8TB2E4qIsq/U5myaCDokQtQcBebMuOMp6/DIRE="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.2"
    hash = "sha256-oC8RWdf1zbMYCtmR0ATy/kCkhIwPR9UqFZSMOKLVF/A="
  [mod."golang.org/x/net"]
    version = "v0.43.0"
    hash = "sha256-bf3iQFrsC8BoarVaS0uSspEFAcr1zHp1uziTtBpwV34="
  [mod."golang.org/x/sys"]
    version = "v0.35.0"
    hash = "sha256-ZKM8pesQE6NAFZeKQ84oPn5JMhGr8g4TSwLYAsHMGSI="
  [mod."golang.org/x/text"]
    version = "v0.28.0"
    hash = "sha256-8UlJniGK+km4Hmrw6XMxELnExgrih7+z8tU26Cntmto="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20250825161204-c5933d9347a5"
    hash = "sha256-GpzwiqnK6YxHTplFjMuJ+f1JHbWBeFlj6L+kn1/pP68="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20250825161204-c5933d9347a5"
    hash = "sha256-eeXJH7HJ98p6at4o+ucIiSkZSg1eGKH24MGNeFeb9lw="
  [mod."google.golang.org/grpc"]
    version = "v1.75.0"
    hash = "sha256-bMJEB2luUeYWwsQWqzuq4Wro2tTKBWGJPuTtzioJcfM="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.8"
    hash = "sha256-yZN8ZON0b5HjUNUSubHst7zbvnMsOzd81tDPYQRtPgM="
