schema = 3

[mod]
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.3"
    hash = "sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.4.0"
    hash = "sha256-lLfcV9z4n94hDhgyXJlde4bFB0hfzlbh+polqcJCwGE="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/grafana/pyroscope-go"]
    version = "v1.2.7"
    hash = "sha256-K1KPw7mn6NApht8UNM+gFj2blEwDciygiZdbcVZUQKA="
  [mod."github.com/grafana/pyroscope-go/godeltaprof"]
    version = "v0.1.9"
    hash = "sha256-bZfcR6K0zmSZISdssoKaQLnwgHElyxnNFh3ZblcnYL8="
  [mod."github.com/grafana/regexp"]
    version = "v0.0.0-20240518133315-a468a5bfb3bc"
    hash = "sha256-bNmTHk8HpaEMthizI+vceMp9R9CQAgmeklsHyveDM3Q="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.27.2"
    hash = "sha256-DVhStnXW+zJ2HUpdNUl2GU0Nkv6xN80gLiDXdxz5gwQ="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.0"
    hash = "sha256-jc5pMU/HCBFOShMcngVwNMhz9wolxjOb579868LtOuk="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.15"
    hash = "sha256-OJCDsZuNUxCLrNRZmnpRpo5clcaasPiUdgWtoVxiA1Y="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.66.1"
    hash = "sha256-bqHPaV9IV70itx63wqwgy2PtxMN0sn5ThVxDmiD7+Tk="
  [mod."github.com/prometheus/otlptranslator"]
    version = "v0.0.2"
    hash = "sha256-KVEqm6oNNIXhMq+iIKfL/VCy5RPweI/+UHIbX7vgGi0="
  [mod."github.com/prometheus/procfs"]
    version = "v0.17.0"
    hash = "sha256-l9fVln5n1kmyoNKhHx69X9uzP0XYqnl1PEjHb7lOdzM="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.11.0"
    hash = "sha256-PUX8dzJtkD8YDZFNqpHnl4qgb0tE1W/DLnL7V+/d1z4="
  [mod."github.com/segmentio/kafka-go"]
    version = "v0.4.49"
    hash = "sha256-imxqc9h4fJbFZ6gP48MaeniLGfSPi1d9Y/4x+1SZdxY="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.1-0.20240121214520-5f936abd7ae8"
    hash = "sha256-AUNFlY6K7s1aoW/vb4pjK84ROdnVZY1i6cOmdeG+wN8="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/spf13/cast"]
    version = "v1.10.0"
    hash = "sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spf13/viper"]
    version = "v1.21.0"
    hash = "sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"]
    version = "v0.63.0"
    hash = "sha256-PQKvLNPsNXpG/PtBUHNaqO643n7m0YO22RXny6Q7A1A="
  [mod."go.opentelemetry.io/contrib/propagators/b3"]
    version = "v1.38.0"
    hash = "sha256-a0wX6pa3BfCK3z5tEFFrh3za8MISvROzGz8B59lyWKY="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.38.0"
    hash = "sha256-OU4EVEGwbopbYZLDBfAelR/4yjzfV+UVp4UFt3UvkOE="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc"]
    version = "v0.14.0"
    hash = "sha256-Wa/qbCfjFc7xbQ+xfiGF47sWIOba4zw/fvKC24IqwHw="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.38.0"
    hash = "sha256-erOjiMK86nZaiKKo2DSpqEUBh8Y+PobuCxCTq7Bj2LM="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.38.0"
    hash = "sha256-uBogIdUQGMo4DLTs3CjYEVeYo+EhJu4wdSMhbX0jhfA="
  [mod."go.opentelemetry.io/otel/exporters/prometheus"]
    version = "v0.60.0"
    hash = "sha256-UcGRFaXw4qEwNq7GvSYg9chUE41Kp5Br888zWpre62o="
  [mod."go.opentelemetry.io/otel/log"]
    version = "v0.14.0"
    hash = "sha256-fVKuFX4/O7RW1CnNLPhHc21FGJxXBZTCr+LBQ1JEl7s="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.38.0"
    hash = "sha256-5W6Yd9nl/eyvL29e9hSfosISpxfSQcBAwkqI4htHWCg="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.38.0"
    hash = "sha256-Qxqf7LEbS8Znp8qeQPbgm0jeFVhZNwV2d5zuKysIKIQ="
  [mod."go.opentelemetry.io/otel/sdk/log"]
    version = "v0.14.0"
    hash = "sha256-/D8QOFQjLZcC0uUesclVA6SAarFswisFoxgWqiNKqr0="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.38.0"
    hash = "sha256-Nahjgwhfx9NOJaM87fVpNFgzMOtJYPMehXKCswV59vI="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.38.0"
    hash = "sha256-gNXUPmsPAw6JVH3YT/xwmRpn5QoDxyzc9kLe/5ldo0o="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.7.1"
    hash = "sha256-5VjS+8TB2E4qIsq/U5myaCDokQtQcBebMuOMp6/DIRE="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.2"
    hash = "sha256-oC8RWdf1zbMYCtmR0ATy/kCkhIwPR9UqFZSMOKLVF/A="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/net"]
    version = "v0.46.1-0.20251013234738-63d1a5100f82"
    hash = "sha256-YXontwMF1ashlNm2X2KlWYOIRy3/L0Wt3hwv7ODBHCc="
  [mod."golang.org/x/sys"]
    version = "v0.37.0"
    hash = "sha256-5aT0xP02sW1o9sfJHtWoGGNVYDdwb9FyiX/n6RAlzPo="
  [mod."golang.org/x/text"]
    version = "v0.30.0"
    hash = "sha256-VPT1Y2zzgdk+Q3Gx8hdwKdxbVh0/Zn/HwDpILCW3ZNA="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20251022142026-3a174f9686a8"
    hash = "sha256-HsnIgmC/vyAMUOh20DbgIEInHYJYzs5Fxpf0ngRziws="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20251022142026-3a174f9686a8"
    hash = "sha256-I3ZNpNjKKvTq4DVNw3wLKrCuORabZ0oYj0KKhOMI/MA="
  [mod."google.golang.org/grpc"]
    version = "v1.77.0"
    hash = "sha256-RDkejy1CQ9em+6Pm0oWevEiWbzHSFo1QNut5uWH9TLE="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.10"
    hash = "sha256-gUrj1qSpjcpRKCBnrYlKMm+P0OSh7B/8EBREstwhD1w="
